app/code/community/Ebizmarts/MailChimp/Model/Observer.php
Mage::getModel('core/cookie')->getLifetime doesn't have any parameters,
and returns
Mage::getStoreConfig(Mage_Core_Model_Cookie::XML_PATH_COOKIE_LIFETIME,
Mage::app()->getStore()->getId()) so the comparisons in
_getCampaignCookie and _getLandingCookie always return true. Both
functions are tested for truthiness when they're used, and
Mage::getModel('core/cookie')->get returns false when the cookie isn't
set, so both function should be able to return the ->get call
=> Stop calling getLifetime

app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
**Steps to reproduce:**
1. Go to Mailchimp, select list that you're using for sync with Magento
2. Navigate to "Add contacts -->  Add a subscriber"
3. Fill email, first & last name
4. Click to "Subscribe" button
**Actual result:**
In Magento we have subscriber, but first & last name are missing
**Expected result:**
In Magento we should have first & last name retrieved from Mailchimp.
=> Fix  first & last name processing on subscribe webhook

app/code/community/Ebizmarts/MailChimp/Model/Observer.php
We've found an issue in latest version of module.
Related forum thread:
https://ebizmarts.com/forums/topics/view/25076
**Steps to reproduce:**
1. Go to frontend and subscribe to newsletter
2. Go to Admin --> Newsletter --> Newsletter Subscribers
3. Select customer which was subscribed and in "Mass Action" list execute "unsubsribe" or "delete" action
**Expected result:**
Subscriber was unsubsribed (or deleted) in Magento and Mailchimp.
**Actual result:**
Subscriber was unsubsribed (or deleted) in Magento, but it wasn't unsubsribed from Mailchimp
=> Fix unsubscribe & delete on Newsletter Subscribers grid

app/code/community/Ebizmarts/MailChimp/Model/Observer.php
**Steps to reproduce:**
1. Subscribe user to the newsletter
2. Go to the magento admin, find this subscriber in the Newsletter Subscriber list
3. Try to delete him
**Actual result:**
Fatal error: Call to undefined method Ebizmarts_MailChimp_Helper_Data::getConfigValue()
**Expected result**
Subscriber should be deleted
=> Deleting Subscribers from magento admin caused an error

app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
`getBatchResponse` method in `/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php` errors if the archive file does not exist and/or the `var/mailchimp` directory does not exist. This pull request adds an additional check to check if the file exists before the curl execution, and will create `var/mailchimp` if the directory does not already exist.
`var/mailchimp` is created within the setup script, but in certain cases where a live deployment system creates a fresh version of the site each time the website is deployed to production, the setup script is not run and the old data in the `var` directory is not retained.
Magneto 1.9.3.2
mc-magento 1.1.6
`getBatchResponse` method in `/app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php` runs with no errors.
`getBatchResponse` …
=> Error in `getBatchResponse` method when `/var/mailchimp` directory does not exist

app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
if they are stored as null make them return 0 instead. MailChimp does not like NULL values.
For some reason, on older install of Magento 1, the tax_total and shipping_total can be set as NULL if there isn't tax or shipping. Don't ask me why. I've run into this enough, thissimple check should solve many people's headaches.
=> Validating tax_total and shipping_total

.gitignore, .travis.yml, README.md, app/code/community/Ebizmarts/MailChimp/Model/Email/TemplateBase.php, composer.json
Make Travis CI able to pass while still running strict tests.
Also contains [commit](087aec7983f4c9474da382ff6df3b84e0b1b5c0b) that makes the module able to pass Magento [Marketplace Technical Review](https://github.com/magento/marketplace-eqp/tree/c82070eca1075569578206430a6ef7975f7eeec1#marketplace-technical-review) minimum demands
To avoid GitHub's API rate limit a token can be generated ([link](https://github.com/settings/tokens/new?scopes=repo)) and given as a environment variable named `GITHUB_TOKEN`.
Thanks to @centerax for laying the groundwork with his Travis config
=> Make Travis pass basic test

app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
The way the code currently is, there is no issue since Magento's autoloader handles improperly cased class names. However, we use a custom autoloader that is a little more strict about the accuracy of class name references. It would be great to ensure the class name references are accurate.
I did a quick search over the codebase for other examples but this was the only one I found.
=> Correcting class name reference

app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
Different currencies in the same store causes Mailchimp to not calculate revenue correctly, modification sends the base values of each store so only one currency per store is sent to Mailchimp.
=> closes #439 Different currencies causes issue with revenue

app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
Currently there is only one dispatch job that is triggered incrementally for each pre-defined value. You can not append data to the array without overriding any function.
This change will dispatch an event to the end of the ```getMergeVars``` function and give the possibility to have more dynamic data inside the array.
=> Added event dispatch after merge of variables for subscriber sync

app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Sales/Order/Grid/Renderer/Mailchimp.php
Due to you are loading each order for each row in the order grid you might case as exception.
Magento throws by default an exception if you load a order which has used a payment method that has been disabled or been removed. Due to the search filter is saved in the session you will not be able to visit the order list any more due to it will constantly throw the same exception until the session is cleared.
=> Removes exception in order grid if for example a used payment method has

app/code/community/Ebizmarts/MailChimp/Model/Observer.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
Check if checkout subscriber ist no returning customer (has no customer id), then add the first+lastname to the subscriber data.
=> add guest checkout name to subscriber data

app/code/community/Ebizmarts/MailChimp/Block/Popup/Emailcatcher.php, app/code/community/Ebizmarts/MailChimp/Model/Observer.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
Closes Issue #668. Use the default Magento method to subscribe checkout subscriber and not the one for the webhook.
Small Fix: setStoreId was called twice in _handleCookie function. Removed one.
=> Closes Issue668

app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimpController.php
Modified the function _isAllowed() added the case of the action createWebhook in the file MailchimpController.php for Magento custom users without Admin permissions.
=> closes #871 added acl permissions to the action createWebhook

app/code/community/Ebizmarts/MailChimp/Helper/Data.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
- The program fails when a registered user subscribe to the newsletter at 'My account->Newsletter' or after place the order.
- Check if the module is enabled before execute the code in the function **getInterestGroups** if the module is disabled the function returns an empty array.
- Modified **testGetInterestGroups** to adapt it to the change in the function **getInterestGroups**
=> Subscription fails when one store view is disabled with the API key in blank

app/code/community/Ebizmarts/MailChimp/Helper/Data.php, app/code/community/Ebizmarts/MailChimp/Model/Observer.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
Modified the functions subscriberSaveAfter and subscriberSaveBefore removed repeated code which caused send double email confirmation subscription.
=> Multiple confirmation email from mailchimp after group subscription

app/code/community/Ebizmarts/MailChimp/Model/Observer.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
Modified the function subscribeSaveBefore to not change the status of the subscribers to 'Not Activated' if the option use Magento emails is enabled and the option double opt-in is enabled too.
=> Subscribers status doesn't change to subscribed if double opt-in is activated using Mandrill

app/code/community/Ebizmarts/MailChimp/Model/Observer.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
- Removed $addColumnConfig from the if statement [here](https://github.com/mailchimp/mc-magento/blob/1.1.12/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L428).
- Implemented the test for the function addColumnToSalesOrderGrid.
=> Display on order grid" also hides Ebizmarts_MailChimp_Block_Adminhtml_Sales_Order_View_Info_Monkey

app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Email/TemplateTest.php
- Modified the function getMail to get the storeId from another way.
- Implemented the test getMail
- Modified the function getMail to adapt it to the test
=> Mandrill default scope disabled enabled on specific website/storeview breaks order comment emails

app/design/frontend/base/default/layout/ebizmarts/mailchimp.xml
Prevent Mage_Core_Exception: Invalid block type: Ebizmarts_MailChimp_Block_Group_Types
=> Fix block type

app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php, app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php, app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/CartsTest.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/OrdersTest.php
- Removed the API call to get email of the customer from the function _getCustomer in the file Carts.php
- Implemented tests for _getCustomer and makeCart.
- Removed the API call to get email of the customer from the function GeneratePOSTPayload in the file Orders.php.
- Implemented test for GeneratePOSTPayload.
- Changed how the id of the customer is created at _buildCustomerData in the file Customers.php
=> Avoid get by email calls when sending orders and carts to mailchimp

lib/Ebizmarts/MailChimp.php
=> Remove POST params if call is get in case the same API object is used in several calls.

app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
- closes #109
- reference #913 if a new product is disabled in the default scope and enabled in the storeView the product will be correctly synced to Mailchimp. 
- closes #904 
- If the product is out of stock or the quantity is negative the product won't send to Mailchimp.
- If the product is disabled that product won't send to Mailchimp.
=> fixed error at the collection with inner join when addFinalPrice

app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php, app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- Changed how the process the mailchimp response if the item is a product and the product is marked as disabled or have the message "This product was deleted because it is disabled in Magento."
- Now if the product was disabled and then enabled before delete the product to send it as new product to Mailchimp chack if the product isMarkedAsDeleted or if the product have the message: "This product was deleted because it is disabled in Magento."
- closes #943
=> Error syncing order with disabled product

app/code/community/Ebizmarts/MailChimp/Helper/Data.php, app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php, app/code/community/Ebizmarts/MailChimp/Model/Observer.php, app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php, app/code/community/Ebizmarts/MailChimp/Model/Subscriber.php, dev/tests/mailchimp/autoload.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ProcessWebhookTest.php
Modifying isUseMagentoEmailsEnabled() return data type, in Data.php, in order to return an int.
Modifying the logic in Observer.php (subscriberSaveAfter() method) in order to make possible the immediately sending subscribers changes.
Adding new constant: const SUBSCRIBE_CONFIRMATION = 'MailChimp_Confirmation';
for knowing when email confirmation is required.
Modifying ObserverTest.php due to the changes made in Observer.php #996 closes
=> Modifying the logic in Observer.php (subscriberSaveAfter() method) in order to make possible the immediately sending subscribers changes.

lib/Ebizmarts/MailChimp.php, lib/Ebizmarts/MailChimp/Exceptions.php, lib/Ebizmarts/MailChimp/Mailchimp_HttpError.php
- Changed the order of the mailchimp error exception params.
- Fixed "params" var "array to string conversion".
Ref. #1021 .
=> Mailchimp exception params fixed

app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Form/Field/Mapfields.php, app/code/community/Ebizmarts/MailChimp/Helper/Data.php, app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php, app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php, app/code/community/Ebizmarts/MailChimp/Model/System/Config/Backend/Mapfield.php, app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MergevarsController.php, dev/tests/mailchimp/autoload.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php, lib/Ebizmarts/MailChimp/Lists.php
Defining new two methods in Helper/Data.php: serialize and unserialize(), which use Zend_Serializer's methods:
https://framework.zend.com/manual/2.3/en/modules/zend.serializer.html,
instead using directly serialize and unserialize() which are deprecated according to MEQP standard.
Reusing the above mentioned methods in: Data.php, MailchimpTags.php, Mapfield.php, Mapfields.php, MergevarsController.php, ProcessWebhook.php
Updating test cases.
closes #1019
=>  serialize() and unserialize() via Zend_Serializer class

app/code/community/Ebizmarts/MailChimp/Helper/Data.php, app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php, app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimperrorsController.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimperrorsControllerTest.php, shell/getMailchimpResponse.php
Ref. #779 .
Fixed camelcase variables names and json decode with assoc param in true.
=> Camel Case variables fix

lib/Ebizmarts/MailChimp/ListsSegments.php
According to the developer documentation (https://mailchimp.com/developer/reference/lists/list-segments/) you should be allowed to send an empty static_segment but the value checker in the code does not allow the same condition. By just checking of the value is not null the developer can send in empty arrays.
=> Added possibility to send empty params

app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php, dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
Registering the product id in **mailchimp_sync_error** column of **mailchimp_ecommerce_sync_data** table, as part of the error message, if is not supported on Mailchimp.
=> Registering the product id if its type is not supported on Mailchimp.

js/ebizmarts/mailchimp/campaignCatcher.js
Ref. #1147 
Changed `$.inArray` for `jQuery.inArray`. This seems to solve the "inArray is not a function" error thrown in google chrome console. Tested also in Firefox.
=> Solved issue with inArray jquery method

app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Customer/Edit/Tab/Mailchimp.php, app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Sales/Order/View/Info/Monkey.php, app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Form/Field/Mapfields.php, app/code/community/Ebizmarts/MailChimp/Block/Checkout/Subscribe.php, app/code/community/Ebizmarts/MailChimp/Block/Checkout/Success/Groups.php, app/code/community/Ebizmarts/MailChimp/Block/Customer/Newsletter/Index.php, app/code/community/Ebizmarts/MailChimp/Block/Group/Type.php, app/code/community/Ebizmarts/MailChimp/Block/Popup/Emailcatcher.php, app/code/community/Ebizmarts/MailChimp/Helper/Data.php, app/design/adminhtml/default/default/template/ebizmarts/mailchimp/customer/tab/mailchimp.phtml, app/design/adminhtml/default/default/template/ebizmarts/mailchimp/sales/order/view/monkey.phtml, app/design/adminhtml/default/default/template/ebizmarts/mailchimp/system/config/form/field/array_dropdown.phtml, app/design/frontend/base/default/template/ebizmarts/mailchimp/checkout/subscribe.phtml, app/design/frontend/base/default/template/ebizmarts/mailchimp/checkout/success/groups.phtml, app/design/frontend/base/default/template/ebizmarts/mailchimp/customer/newsletter/index.phtml, app/design/frontend/base/default/template/ebizmarts/mailchimp/group/type/checkboxes.phtml, app/design/frontend/base/default/template/ebizmarts/mailchimp/group/type/dropdown.phtml, app/design/frontend/base/default/template/ebizmarts/mailchimp/group/type/radio.phtml, app/design/frontend/base/default/template/ebizmarts/mailchimp/popup/emailcatcher.phtml, dev/tests/mailchimp/autoload.php
Ref. #1114 
Due the M1.7 error with EscapeQuote method because it doesn't exists until version 1.8, we created a function in our helper to call the same PHP version that escapeQuote calls in Magento +1.8.
=> Replaced quoteEscape for mcEscapeQuote method
