mailchimp/mc-magento

- app/code/community/Ebizmarts/MailChimp/Helper/Oauth2.php
Use https protocol as redirect url, because original url has http to https redirect.
> Use https protocol for redirect url

- app/code/community/Ebizmarts/MailChimp/sql/mailchimp_setup/mysql4-upgrade-1.1.5-1.1.5.6.php
https://github.com/mailchimp/mc-magento/issues/189
(see this issue)
> Added pagination for too huge collections in data-upgrade

- app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php
- app/code/community/Ebizmarts/MailChimp/Model/Email/TemplateBase.php
> Add compatibility with SMTPPro Module

- .travis.yml
This build will fail on Travis, that is expected.
> Travis configuration.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/CustomersTest.php
performance improcements on customers batch generation. ref: https://github.com/mailchimp/mc-magento/issues/91
> Customers batch json performance

- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/SubscribersTest.php
> Fix for issue #235.

- app/code/community/Ebizmarts/MailChimp/Model/Cron.php
- app/code/community/Ebizmarts/MailChimp/etc/config.xml
> Split cron jobs

- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- app/code/community/Ebizmarts/MailChimp/etc/config.xml
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
> Moto orders added to a campaign

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/Model/Mysql4/Webhookrequest.php
- app/code/community/Ebizmarts/MailChimp/Model/Mysql4/Webhookrequest/Collection.php
- app/code/community/Ebizmarts/MailChimp/Model/Webhookrequest.php
Webhooks not being properly processed due to class name. #288
> Fixed testing issues.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
> tests and fix for when getChildrenIds returns "empty"

- app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
Add a limit
closes #308 and closes #295
> Add a addFieldToFilter to select only the no processed regiters

- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
Do not translate customer group name, so they are the same over all stores/lists
> Do not translate customer group

- app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> Added checking when list changes and no subscriber object is returned

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
https://github.com/mailchimp/mc-magento/issues/343
> Products decimal price not showing

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/sql/mailchimp_setup/mysql4-upgrade-1.1.6.6-1.1.6.7.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/CustomersTest.php
> Fix customer subsribed incorrect list and duplicate entries in newsletter grid.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
> Added separated error message for api-errors in public section

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/ResetEcommerceData.php
- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
- app/code/community/Ebizmarts/MailChimp/Model/Config.php
- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Backend/Active.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Backend/Apikey.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Backend/Ecommerce.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Backend/List.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Account.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/SubscribersTest.php
> Fix sending product data when product flat tables are enabled.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> Problem with order edit causing "Resource not found error" solved.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
> Remove province_code if null

- app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> Ignore profile web hooks for customers where names don't change.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
> Confirm that api exists before calling status function.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
> Separate address data

- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
> Set deleted subscribers in Magento as unsubscribed in MailChimp.

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
- app/code/community/Ebizmarts/MailChimp/Model/Config.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/BatchLimit.php
- app/code/community/Ebizmarts/MailChimp/etc/config.xml
- app/code/community/Ebizmarts/MailChimp/etc/system.xml
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
> Add configuration fields for batch limits on each object type.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
> Send subscriber address as addr.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
Optimized function getProductCategories by using collection instead of loading model in a loop.
Also, get only active categories sort by parent to child for better category name flow.
> Optimize function getProductCategories.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> Fix for orders sending one more in the customer order count.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
> Avoid showing error message to customer in front end when subscription fails

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
Looks like after this code was merged, branch was deleted without merging to develop. ref: #486
> Reapplying PR #486

- app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> Fix for error: Call to undefined method unsubscribeMember().

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Account.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Account.php
> Add details at subscriber amount display in account details.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
Send the website price when available, otherwise send default price
> closes #511 Send price for website when available

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
> Set current store before getting media URL to get the correct domain.

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoRules.php
- app/code/community/Ebizmarts/MailChimp/Model/Config.php
- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- app/code/community/Ebizmarts/MailChimp/controllers/CartController.php
- app/code/community/Ebizmarts/MailChimp/etc/config.xml
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/BatchesTest.php
> Fix image url with cache

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- app/code/community/Ebizmarts/MailChimp/etc/config.xml
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/BatchesTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
> Send parent image when child has no image and belongs to a configurable

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Sales/Order/Grid/Renderer/Mailchimp.php
> Show monkey image in order grid only when campaign_id or abandonedcart_flag present in order.

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
> Send parent price when child product not visible.

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
MCJs is blocking pageload - fix to load async instead
> load MCJs async

- app/code/community/Ebizmarts/MailChimp/Model/Email/Template.php
> Filter sending message with correct store id in stead of checking only the default scope

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
> Added try & catch for webhook delete failure.

- app/code/community/Ebizmarts/MailChimp/etc/config.xml
- app/code/community/Ebizmarts/MailChimp/sql/mailchimp_setup/mysql4-upgrade-1.1.10-1.1.11.php
> Add index for type column in mailchimp_ecommerce_sync_data table.

- js/ebizmarts/mailchimp/campaignCatcher.js
> Only set landing page when it does not exist.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
> Check if parent has been sent already before updating it when a childproduct is modified

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
> Allowed memory size exhausted error message, when resetting the store or when resetting errors

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Mailchimperrors/Grid.php
- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoRules.php
- app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
> Fixed problem with some installations when retrieving a collection.

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php
- app/code/community/Ebizmarts/MailChimp/Model/Config.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/PromoCodesTest.php
> Fix resend data

- dev/tests/mailchimp/tests/lib/Ebizmarts/MailChimpTest.php
- lib/Ebizmarts/MailChimp.php
> Lib properties

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
> Improve performance when retrieving the last date of purchase.

- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
enable checkout subscription even if isEcomSyncDataEnabled is not enabled for this storeview
> closes issue 657

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
Send products with no description and strip html tags from description
> closes #747 Send products with no description

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimperrorsController.php
> Show correct error message when trying to download a response that does not exist in the MailChimp server anymore.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoRules.php
> Add case to get website domain correctly.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/CustomersTest.php
Customer batch limit was not working. Whole code portion was revised to make it more efficient.
> #806 Customer batch limit not working

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/BatchesTest.php
Stop syncing process if no connection to MailChimp's API available.
> closes #738 Stop syncing process if can't connect to MC API.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
- If sku is null, send empty string to Mailchimp so products can be used in promotional emails
> closes #814 Send products with sku = null

- lib/Ebizmarts/MailChimp/EcommerceOrdersLines.php
- lib/Ebizmarts/MailChimp/ListsSegments.php
- lib/Ebizmarts/MailChimp/ListsSegmentsMembers.php
There is several references to constant in a class that does not exist. This PR changes the classname to the one that it is expected to be.
> Issue with references to unknown constants

- README.md
Mailchimp tutorial about this integration includes images. Please merge this PR so people can navigate to the Mailchimp tutorials
> create a reference to the Mailchimp tutorials

- CHANGELOG.md
> Pre release 1.1.14

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/BatchesTest.php
- Add ping to API after checking if Ecommerce data is enabled and working
> The program fails when set up the extension in one store view and disable another store view leaving the api key in blank

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
Fixed an error in the function handleEcommerceBatches after added ping to API after checking if Ecommerce data is enabled and working.
Related issues:  
closes #846  
closes #863
> closes #863#846#864 fixed an error in the function handleEcommerceBatches

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/StoresTest.php
> Avoid real time call when MCJs URL is not available.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
Statuses changed partially_paid and partially_shipped
> Order status fixed spelling error. closes #868

- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
Implemented the test for the function handleCustomerGroups and modified the function handleCustomerGroups to adapt it to the test
> Unit test handle customer groups

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
- Implemented the function markSpecialPrices.
- Implemented the test for the function markSpecialPrices.
- Implemented the test for joinMailchimpSyncData
> Special price attribute not sent to mailchimp

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Account.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
> The store data is currently being migrated to the new version

- app/code/community/Ebizmarts/MailChimp/etc/system.xml
> added term of use under the combobox to enable the extension

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
> fixed error when click on button resend ecommerce data

- app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php
Fix missing log on error
Advice would be to also give some more feedback to the user in the popup message
> Fix missing log on error

- app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php
Reverts mailchimp/mc-magento#916
> Revert "Fix missing log on error"

- app/design/frontend/base/default/layout/ebizmarts/mailchimp.xml
> Remove template and fix name for group type block.

- app/code/community/Ebizmarts/MailChimp/controllers/GroupController.php
- app/locale/en_US/Ebizmarts_MailChimp.csv
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/controllers/GroupControllerTest.php
> Thanks for share your interest with us.
should be
> Thanks for shar**ing** your interest with us.
> fixed grammar in success message

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php
> Solves problem when resetting errors for message Undefined index customer_id.

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/CreateMergeFields.php
- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/design/adminhtml/default/default/template/ebizmarts/mailchimp/system/config/createmergefields.phtml
- app/locale/en_US/Ebizmarts_MailChimp.csv
> Display a better message error

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
- Changed how get the child's product collection
- Adapted test to the changes 
- closes #930
> Orders doesnt sync with mailchimp when the order have a child product

- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
- added missed function at observer 
- fixed error in Carts.php
- closes #938
> Missed function at observer at pre-release 1.1.16

- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
- added missed function at observer
- fixed error in Carts.php
- closes #938
> Missed function at observerin develop branch

- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- Added strtolower when get the email of the customer
- closes #952
> Customer and subscriber with same email sent to mailchimp with different id

- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoRules.php
> Delete promo codes before promo rule deletion #967

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
builMailchimpDataJoinForSpecialPrices, executeMailchimpDataJoin,builMailchimpDataJoinForSpecialPrices closes #964
> Separated functions for special prices query 

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Notifications.php
- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php
- app/design/adminhtml/default/default/layout/ebizmarts/mailchimp.xml
Popup added in notification.
Function deleteFlushMagentoCacheFlag moved to where products are set to be resend.
Tests fixed for PHP7
> Popup resend 891

- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
> #970 set value for $syncDelta on calls to _updateSyncData function instead null parameter

- app/code/community/Ebizmarts/MailChimp/Block/Checkout/Success/Groups.php
- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/controllers/GroupController.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
> Fixing magento1.7 changing the way of accessing the order from checkout session

- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/OrdersTest.php
Fixing currency format for orders email notifications received from Mailchimp automation closes #982
> Fixing currency format for orders email notifications received from Mailchimp automation #982

- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTagsTest.php
to avoid entries (warnings) #936
> constant GENDER added to class mailchimptags, isset validation in getMailChimpTagValue

- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
Fixing error which happened while trying to subscribe a customer created from backend closes #990
> Fixing error which happened while trying to subscribe a customer created from backend #990

- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/OrdersTest.php
added calculateRowTotal function closes #999
> Incoherence in order item price #999

- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/OrdersTest.php
Reverts mailchimp/mc-magento#1000
> Revert "Incoherence in order item price #999"

- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/WebhookDelete.php
- app/code/community/Ebizmarts/MailChimp/etc/system.xml
Rename delete customer account option #992 closes
> Rename delete customer account option#992

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Sales/Order/Grid/Renderer/Mailchimp.php
- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Form/Field/Mapfields.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/CustomersTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/OrdersTest.php
Ref. #1007 .
Typos added in last versions and corrections accidentally are fixed.
> Typos in methods solved.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/CustomersTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
> Certain Merge fields not transferred #425

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Notifications.php
- app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php
- app/design/adminhtml/default/default/template/ebizmarts/mailchimp/notifications.phtml
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceControllerTest.php
> Cannot resend Ecommerce data from particular scope

- app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/Ecommerce/Resendecommercedata/Form.php
> Cannot resend Ecommerce data from particular scope... #1017

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
> Call to undefined method joinMailchimpSyncDataWithoutWhere #1014

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Helper/DataTest.php
- js/ebizmarts/mailchimp/config.js
Validating if "self::DATA_NOT_SENT_TO_MAILCHIMP" and "self::DATA_SENT_TO_MAILCHIMP" indexes exist before ben used for reading. closes #1050
> Validating if indexes exist before been used while reading an array closes #1050

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
Changing the getSyncBatchesModel() method: returning a new Ebizmarts_MailChimp_Model_Synchbatches model object, instead reusing the same object while the processing responses from Mailchimp API. closes #1057
> Changing the getSyncBatchesModel() method: returning a new Ebizmarts_MailChimp_Model_Synchbatches object.

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
Optimizing modifyCounterDataSentToMailchimp() method closes #1050
> Optimizing modifyCounterDataSentToMailchimp() method.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
> Use empty function correctly #1039

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
> Product resend internal problem #1066

- README.md
Editing readme with typo on text
> Fix typo readme on mailchimp magento

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php
- app/code/community/Ebizmarts/MailChimp/Model/Config.php
- app/code/community/Ebizmarts/MailChimp/Model/System/Config/Backend/Store.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/BatchesTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/ProductsTest.php
Removing all uses of GENERAL_ECOMMMINSYNCDATEFLAG variable. And hence delete the method: getEcommMinSyncDateFlag() and its uses.
Adding "break" loop control in getIfConfigExistsForScope() method, in order of stop iteration through the collection when condition is satisfied.
Modifying ProductsTest.php closes #1072
> Removing all uses of GENERAL_ECOMMMINSYNCDATEFLAG variable.

- js/ebizmarts/mailchimp/campaignCatcher.js
Matching urls like: 
{base_url}/?mc_cid={campaign_id}
{base_url}?mc_cid={campaign_id}
{base_url}?utm_source=mailchimp&mc_cid={campaign_id}
closes #1071
> Matching urls containing mc_cid as variable for campaign id.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/BatchesTest.php
Checking is_syncing flag status. If not syncing, then all the carts are sent.
> Checking is_syncing flag status. If not syncing, then all the carts are sent.

- js/ebizmarts/mailchimp/campaignCatcher.js
Improving campaignCatcher.js. closes #1071
> Improving campaignCatcher.js.

- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/OrdersTest.php
> Solved wrong store Id in carts and Orders when product is modified

- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
Removing protected function getProductPrice() because it had the same logic of getMailchimpFinalPrice(). closes #1094
> Removing protected function getProductPrice().

- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php
- app/code/community/Ebizmarts/MailChimp/Model/Resource/Ecommercesyncdata/Collection.php
- app/code/community/Ebizmarts/MailChimp/Model/Resource/Interestgroup/Collection.php
- app/code/community/Ebizmarts/MailChimp/Model/Resource/Mailchimperrors/Collection.php
- app/code/community/Ebizmarts/MailChimp/Model/Resource/Webhookrequest/Collection.php
Modifying some some PHP docs in order to throw "Ebizmarts_MailChimp_Helper_Data_ApiKeyException" properly.
Solving some ref. #779 issues related to 120 characters limit exceeded.
closes #1098
> Handling Ebizmarts_MailChimp_Helper_Data_ApiKeyException

- app/code/community/Ebizmarts/MailChimp/Model/ClearEcommerce.php
Possible fix for #1112 Remove empty values
https://github.com/mailchimp/mc-magento/issues/1112
> Possible fix for #1112

- app/code/community/Ebizmarts/MailChimp/controllers/CartController.php
- app/code/community/Ebizmarts/MailChimp/etc/adminhtml.xml
- app/locale/en_US/Ebizmarts_MailChimp.csv
> Allow translation capability on CartController.php

- app/code/community/Ebizmarts/MailChimp/etc/adminhtml.xml
> Add Mailchimp configuration link at Newsletter -> Mailchimp menu

- app/code/community/Ebizmarts/MailChimp/Helper/Curl.php
- app/code/community/Ebizmarts/MailChimp/Helper/Data.php
- app/code/community/Ebizmarts/MailChimp/Helper/File.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Batches.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/ItemSynchronizer.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php
- app/code/community/Ebizmarts/MailChimp/Model/Ecommercesyncdata.php
- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- app/code/community/Ebizmarts/MailChimp/Model/Resource/Ecommercesyncdata/Customers/Collection.php
- dev/tests/mailchimp/autoload.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/CartsTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/OrdersTest.php
- lib/Ebizmarts/MailChimp.php
> Fixing the syncing with Mailchimp. Issues of curl requests.

- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php
- app/code/community/Ebizmarts/MailChimp/Model/Api/PromoRules.php
- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/PromoCodesTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/PromoRulesTest.php
Solving the syncing of promo codes and promo rules issue.
ref #1128
> Promo codes and promo rules issues solved.

- js/ebizmarts/mailchimp/config.js
Ref. #1136.
Functions that loads list and subscribers moved inside the If that confirms that the json response is valid. This avoid the Stack of the loading gif while loading that data.
> List load function moved inside response confirmation if

- app/code/community/Ebizmarts/MailChimp/Model/Adminhtml/Resendecommercedata/Comment.php
- app/code/community/Ebizmarts/MailChimp/Model/Adminhtml/Resendsubscribers/Comment.php
- app/code/community/Ebizmarts/MailChimp/Model/Adminhtml/Reseterrors/Comment.php
- app/code/community/Ebizmarts/MailChimp/etc/system.xml
- app/locale/en_US/Ebizmarts_MailChimp.csv
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Adminhtml/Resendecommercedata/CommentTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Adminhtml/Resendsubscribers/CommentTest.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Adminhtml/Reseterrors/CommentTest.php
> Add explanation for Resend and Reset buttons with which scope will be deleted.

- app/code/community/Ebizmarts/MailChimp/Model/Observer.php
- dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
- js/ebizmarts/mailchimp/campaignCatcher.js
> variable mcEid removed from observer and CampaignCatcher

- app/code/community/Ebizmarts/MailChimp/Helper/Curl.php
- lib/Mandrill/Mandrill.php
Using Ebizmarts_MailChimp_Helper_Curl for making the requests to Mandrill API.
loses #1157
> Using Ebizmarts_MailChimp_Helper_Curl for making the requests to Mandrill API

- app/code/community/Ebizmarts/MailChimp/Helper/Curl.php
- lib/Mandrill/Mandrill.php
> Fix Mandrill info data.

- lib/Ebizmarts/MailChimp.php
Ref. #1155 
Added curl http request version to mailchimp's Lib.
> Added version 1.1 of curl http version
